# ----- Coin Info cryptoland.com -----

NETWORK_PASSPHRASE="Public Global Stellar Network ; September 2015"

ACCOUNTS=["GBNTDFZ6AAEK6DS2ID5STINF7Q7JLRESZRWYTMREEU3JY67PS6SE6L4G","GDUPVSCFLPYWMQ3B3U6XNEBA3HRRZ7XJBDO2YUCWVXIGN72KME2OR2YY"]

[DOCUMENTATION]
ORG_NAME="Cryptoland"
ORG_DBA="Crypto Movez LLC"
ORG_URL="cryptolandico.com"
ORG_LOGO="https://cryptolandassets.s3.us-east-2.amazonaws.com/Cryptoland_LOGO.png"
ORG_DESCRIPTION="Cryptoland"
ORG_OFFICIAL_EMAIL="corey@cryptocorey.com"

[[PRINCIPALS]]
name="Corey Chadwick"
email="corey@cryptocorey.com"
github="teamonepercent"

[[CURRENCIES]]
code="CRYPTO"
issuer="GBNTDFZ6AAEK6DS2ID5STINF7Q7JLRESZRWYTMREEU3JY67PS6SE6L4G"
display_decimals=2
anchor_asset_type="crypto"
anchor_asset="XLM"
name="CRYPTOLAND"
desc="Cryptoland"
image="https://cryptolandassets.s3.us-east-2.amazonaws.com/Cryptoland_LOGO.png"